version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9050:9000"
      - "9051:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    restart: unless-stopped